# Generated by Django 3.2.5 on 2021-07-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='title',
            field=models.CharField(choices=[('netflix', 'Netflix'), ('nbc', 'NBC'), ('prime', 'Prime Video'), ('disney', 'Disney')], max_length=50),
        ),
    ]
